all:
  children:
    all_devices:
      hosts:
        r1:
          ansible_host: 10.1.254.1
        r2:
          ansible_host: 10.1.254.2
        r3:
          ansible_host: 10.2.254.3
        r4:
          ansible_host: 10.2.254.4
        r5:
          ansible_host: 10.2.254.5
        r6:
          ansible_host: 10.3.254.6

    ospfv3_routers:
      hosts:
        r3:
        r4:
        r5:

    eigrp_routers:
      hosts:
        r1:
        r2:
