services:
  pyats:
    network_mode: host
    env_file: .env
    # (optional explicit)
    environment:
      - PYATS_USERNAME=${PYATS_USERNAME}
      - PYATS_PASSWORD=${PYATS_PASSWORD}
      - PYATS_ENABLE_PASSWORD=${PYATS_ENABLE_PASSWORD:-${PYATS_PASSWORD}}
