[project]
name = "myansible"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ansible>=11.9.0",
    "ansible-pylibssh>=1.2.2",
    "paramiko>=4.0.0",
    "python-dotenv>=1.1.1",
]
