devices:
  - name: r1
    ip: 10.0.0.248
    os: iosxe
    type: router
    mgmt_int: Loopback0
    expected_hostname: R1

  - name: sw2-1
    ip: 10.2.1.1
    os: iosxe
    type: switch
    mgmt_int: Loopback0
    expected_hostname: SW2-1

