#!/usr/bin/env bash

set -eu

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RESET='\033[0m'

repo_root=${1:?Missing repository root}
branch=${2:?Missing branch name}
commit=${3:?Missing commit SHA}

playbook_dir="$repo_root/playbooks"

log_dir="$repo_root/logs" && mkdir -p "$log_dir"

ansible_log_file="$log_dir/ansible-pre-cicd-$commit.log"
git_log_file="$log_dir/git-hooks.log"
tests_dir="$repo_root/tests"
pyats_log_file="$log_dir/pyats-pre-cicd-$commit.log"

exec > >(tee -a >(sed $'s/\033\\[[0-9;]*m//g' >>"$git_log_file")) 2>&1

cd "$repo_root"

logger() {
    local prefix=${1:-cicd}
    ts=$(date '+%Y-%m-%d %H:%M:%S')
    printf '%s [%s-commit]:' "$ts" "$prefix"
}

rollback_config() {
    echo "$(logger "pre") Running Ansible Rollback..."
    if ! uv run ansible-playbook \
        -i inventory/inventory.yml \
        "$playbook_dir"/utils/rollback_config.yml >>"$ansible_log_file" 2>&1; then
        printf "${RED}%s Ansible rollback-config failed, exiting pipeline${RESET}\n" \
            "$(logger "pre")"
        exit 1
    fi
    printf "${GREEN}%s Ansible rollback-config completed successfully${RESET}\n" \
        "$(logger "pre")"
    printf "${RED}%s Commit %s aborted due to pipeline failure, see logs${RESET}\n" \
        "$(logger "pre")" "$commit"
    exit 1
}

commit_config() {
    echo "$(logger "pre") Running Ansible Commit..."
    if ! uv run ansible-playbook \
        -i inventory/inventory.yml \
        "$playbook_dir"/utils/commit_config.yml >>"$ansible_log_file" 2>&1; then
        printf "${RED}%s Ansible commit-config failed, exiting pipeline${RESET}\n" \
            "$(logger "pre")"
        exit 1
    fi
    printf "${GREEN}%s Ansible commit-config completed successfully${RESET}\n" \
        "$(logger "pre")"
}

if [[ -z "$branch" ]]; then
    printf "${YELLOW}%s Detached HEAD; skipping CI/CD${RESET}" \
        "$(logger "pre")"
    exit 0
fi

if [[ "$branch" = "main" ]]; then
    echo "$(logger "pre") Commit is on main; skipping CI/CD."
    printf "${YELLOW}%s Commit is on main; skipping CI/CD${RESET}" \
        "$(logger "pre")"
    exit 0
fi

playbooks=false
for file in "$playbook_dir"/*.yml "$playbook_dir"/*.yaml; do
    if [[ -f "$file" ]]; then
        playbooks=true
        break
    fi
done

if [[ "$playbooks" = true ]]; then
    echo "$(logger "pre") Local CI/CD started"
    echo "$(logger "pre") Repository: $repo_root"
    echo "$(logger "pre") Branch: $branch"
    echo "$(logger "pre") Commit: $commit"

    # sync python environment
    echo "$(logger "pre") Sync'ing python environment..."
    uv python install 3.14 >/dev/null 2>&1
    uv sync --python 3.14 >/dev/null 2>&1
    printf "${YELLOW}%s Python environment sync complete${RESET}\n" \
        "$(logger "pre")"

    # Run Ansible syntax check
    echo "$(logger "pre") Running Ansible Syntax Check..."

    if ! find playbooks -maxdepth 1 -type f \
        \( -name '*.yml' -o -name '*.yaml' \) \
        -exec uv run ansible-playbook \
        --syntax-check \
        -i inventory/inventory.yml {} + >>"$ansible_log_file" 2>&1; then
        printf "${RED}%s Ansible syntax check failed${RESET}\n" \
            "$(logger "pre")"
        exit 1
    fi
    printf "${GREEN}%s Ansible syntax check successful${RESET}\n" \
        "$(logger "pre")"
fi

# Run Ansible backups
backup=false
backup_file=""
for file in "$playbook_dir/"*backup*.yml "$playbook_dir/"*backup*.yaml; do
    if [[ -f "$file" ]]; then
        backup=true
        backup_file=${file##*/}
        break
    fi
done

if [[ "$backup" = true ]]; then
    echo "$(logger "pre") Runnning Ansible Backups..."
    if ! uv run ansible-playbook \
        -i inventory/inventory.yml \
        "$playbook_dir"/"$backup_file" >>"$ansible_log_file" 2>&1; then
        printf "${RED}%s Ansible backups failed, exiting pipeline${RESET}\n" \
            "$(logger "pre")"
        exit 1
    fi
    printf "${GREEN}%s Ansible backups completed successfully${RESET}\n" \
        "$(logger "pre")"
    printf "${YELLOW}%s Backups saved to %s/backups${RESET}\n" \
        "$(logger "pre")" "$repo_root"
fi

# Run Ansible commit-config
if [[ "$playbooks" = true ]]; then
    commit_config
fi

# Failures after this point run the rollback_config.yml playbook

# Run Ansible playbooks
if [[ "$playbooks" = true ]]; then
    echo "$(logger "pre") Running Ansible playbooks..."
    for playbook in playbooks/*.yml playbooks/*.yaml; do
        [[ -f "$playbook" ]] || continue

        case ${playbook##*/} in
        *backup*.yml | *backup*.yaml)
            continue
            ;;
        esac

        echo "$(logger "pre") Running: $playbook"

        if ! uv run ansible-playbook \
            -i inventory/inventory.yml \
            "$playbook" >>"$ansible_log_file" 2>&1; then
            printf "${RED}%s Ansible playbook failed: %s${RESET}\n" \
                "$(logger "pre")" "$playbook"
            rollback_config
        fi
    done
    printf "${GREEN}%s Ansible playbooks completed successfully${RESET}\n" \
        "$(logger "pre")"
fi

# Run pyATS tests
pyats_status=0
if [[ -f "$tests_dir"/job.py ]]; then
    echo "$(logger "pre") Running pyATS tests..."

    if uv run pyats run job tests/job.py --no-mail --no-archive >>"$pyats_log_file" 2>&1; then
        printf "${GREEN}%s pyATS tests completed successfully${RESET}\n" \
            "$(logger "pre")"
    else
        pyats_status=$?
        printf "${RED}%s pyATS tests failed with status %s${RESET}\n" \
            "$(logger "pre")" "$pyats_status"
        rollback_config
    fi
fi

# Commit the config is all playbooks and tests passed
commit_config

if [[ "$playbooks" = true || "$backup" = true ]]; then
    printf "${GREEN}%s Local pre-commit CI/CD completed successfully for %s at %s${RESET}\n" \
        "$(logger "pre")" "$branch" "$commit"
fi
