#!/usr/bin/env bash

set -eu

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
RESET='\033[0m'

logger() {
    local prefix=${1:-cicd}
    ts=$(date '+%Y-%m-%d %H:%M:%S')
    printf '%s [%s-commit]:' "$ts" "$prefix"
}

repo_root=${1:?Missing repository root}
branch=${2:?Missing branch name}
commit=${3:?Missing commit SHA}

playbook_dir="$repo_root/playbooks"

log_dir="$repo_root/logs" && mkdir -p "$log_dir"

ts=$(date '+%Y%m%d-%H%M%S')
ansible_log_file="$log_dir/ansible-pre-cicd-$ts-$$.log"

cd "$repo_root"

playbooks=false
for file in "$playbook_dir"/*.yml "$playbook_dir"/*.yaml; do
    if [[ -f "$file" ]]; then
        playbooks=true
        break
    fi
done

if [[ "$playbooks" = true ]]; then
    echo ""
    echo "$(logger "pre") Local CI/CD started"
    echo "$(logger "pre") Repository: $repo_root"
    echo "$(logger "pre") Branch:     $branch"
    echo "$(logger "pre") Commit:     $commit"

    # sync python environment
    echo ""
    echo "$(logger "pre") Sync'ing python environment..."
    echo ""
    uv python install 3.14
    uv sync --python 3.14
    echo ""
    printf "${YELLOW}%s Python environment sync complete${RESET}\n" \
        "$(logger "pre")"
    echo ""
fi

# Ansible syntax check
if [[ "$playbooks" = true ]]; then
    echo "$(logger "pre") Running Ansible Syntax Check..."
    echo ""

    if ! find playbooks -maxdepth 1 -type f \
        \( -name '*.yml' -o -name '*.yaml' \) \
        -exec uv run ansible-playbook \
        --syntax-check \
        -i inventory/inventory.yml {} + >>"$ansible_log_file" 2>&1; then
        printf "${RED}%s Ansible syntax check failed${RESET}\n" \
            "$(logger "pre")"
        echo ""
        exit 1
    fi
    echo ""
    printf "${GREEN}%s Ansible syntax check successful${RESET}\n" \
        "$(logger "pre")"
    echo ""
fi

# Ansible backups
backup=false
backup_file=""
for file in "$playbook_dir/"config_backup*.yml "$playbook_dir/"config_backup*.yaml; do
    if [[ -f "$file" ]]; then
        backup=true
        backup_file=${file##*/}
        break
    fi
done

if [[ "$backup" = true ]]; then
    echo "$(logger "pre") Runnning Ansible Backups..."
    echo ""
    if ! uv run ansible-playbook \
        -i inventory/inventory.yml \
        "$playbook_dir"/"$backup_file" >>"$ansible_log_file" 2>&1; then
        printf "${RED}%s Ansible backups failed, exiting pipeline${RESET}\n" \
            "$(logger "pre")"
        echo ""
        exit 1
    fi
    printf "${GREEN}%s Ansible backups completed successfully${RESET}\n" \
        "$(logger "pre")"
    printf "${YELLOW}%s Backups saved to %s/backups${RESET}\n" \
        "$(logger "pre")" "$repo_root"
    echo ""
fi

if [[ "$playbooks" = true || "$backup" = true ]]; then
    printf "${GREEN}%s Local CI/CD completed successfully for %s at %s${RESET}\n" \
        "$(logger "pre")" "$branch" "$commit"
    echo ""
fi
