---
- name: Show commands
  hosts: all_devices
  gather_facts: false

  tasks:
    - name: Configuration commit
      cisco.ios.ios_command:
        commands:
          - write memory
      register: commit

    - name: Results
      ansible.builtin.debug:
        var: commit.stdout
