---
- name: Show commands
  hosts: all_devices
  gather_facts: false

  tasks:
    - name: Configuration rollback
      cisco.ios.ios_command:
        commands:
          - configure replace nvram:startup-config force
      register: rollback

    - name: Results
      ansible.builtin.debug:
        var: rollback.stdout
