---
# Testingrassia
- name: Push config to Cisco IOS-XE devices
  hosts: iosxe
  gather_facts: no

  tasks:
    - name: Set project root
      set_fact:
        root: "/home/rickey/Scripts/myAnsible/"

    - name: Check for configuration changes
      stat:
        path: "{{ root }}/configs/{{ inventory_hostname }}_ntp.cfg"
      register: config_changes

    - name: Push NTP Configuration
      cisco.ios.ios_config:
        src: "{{ root }}/configs/{{ inventory_hostname }}_ntp.cfg"
        save_when: changed
      when: config_changes.stat.exists
