---
- name: Commands for r2
  hosts: r2
  gather_facts: no

  tasks:
    
    - import_tasks: infra/01_backup_tasks.yml

    - name: Static NAT Configuration
      cisco.ios.ios_config:
        lines:
          - interface g1
          - ip nat outside
          - interface g2
          - ip nat outside
          - ip nat inside source static 192.168.1.10 172.16.1.1
