# Testing
---
- name: Commands for r2
  hosts: r2
  gather_facts: no

  tasks:
    
    - import_tasks: infra/01_backup_tasks.yml

    - name: Show BGP Table for r2
      cisco.ios.ios_command:
        commands:
          - show bgp ipv4 unicast
