---
- name: Commands for r2
  hosts: r2
  gather_facts: no

  tasks:
    
    - import_tasks: infra/01_backup_tasks.yml

    - name: Static NAT Configuration
      cisco.ios.ios_config:
        lines:
          - interface g1
          - ip nat outside
          - exit
          - interface g2
          - ip nat inside
          - exit
          - no ip nat inside source static 192.168.1.10 172.16.1.1
          - ip access-list standard NAT
          - 10 permit 192.168.1.0 0.0.0.255
          - exit
          - no ip nat pool NAT_POOL 172.16.1.1 172.16.1.10 netmask 255.255.255.0
          - no ip nat inside source list NAT pool NAT_POOL
          - ip nat inside source list 20 interface g1 overload
          - end

