---
- name: Configuration Template
  hosts: all_devices
  gather_facts: false

  tasks:
    - name: Configuration template
      cisco.ios.ios_config:
        parents:
          - interface Ethernet0/0
        lines:
          - description configured by netdevops
        save_when: changed

    - name: Verify configuration change
      cisco.ios.ios_command:
        commands:
          - show running-config interface Ethernet0/0
      register: interface_description
      changed_when: false

    - name: Validate configuration change
      ansible.builtin.assert:
        that:
          - "'configured by netdevops' in interface_description.stdout[0]"
        fail_msg: "Configuration change failed on {{ inventory_hostname }}"
