---
- name: Config Backup - console connnections
  hosts: consoles
  gather_facts: false

  tasks:
    - name: Timestamp
      set_fact:
        timestamp: "{{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"

    - name: Show running-config
      ansible.builtin.expect:
        command: "telnet {{ ansible_host }} {{ telnet_port }}"
        timeout: 10
        echo: true
        responses:
          "(?i)Escape character is \\'\\^\\]\\'\\.\\s*$": "\r"

          '(?i)Username:\s*$': "{{ telnet_user }}"
          '(?i)Password:\s*$': "{{ telnet_password }}"

          # Exit the local Telnet client cleanly.
          '(?i)telnet>\s*$': "quit"

          "(?i)Press RETURN to get started\\.": "\r"

          # Each successive IOS prompt sends the next response.
          '(?m)^(?!telnet>)[^\r\n]*[>#]\s*$':
            - "terminal length 0"
            - "show running-config"
            - "terminal length 24"
            - "\u001d"
      register: config_output
      changed_when: false
      delegate_to: localhost
      vars:
        ansible_python_interpreter: "{{ ansible_playbook_python }}"

    - name: Verify backup directory
      file:
        path: "backups"
        state: directory
        mode: "0755"

    - name: Save running-config
      ansible.builtin.copy:
        content: "{{ config_output.stdout | replace('\\'', '') }}"
        dest: "backups/{{ inventory_hostname }}-running-config-{{ timestamp }}.cfg"
