ansible_connection: ansible.netcommon.network_cli
ansible_network_os: cisco.ios.ios

ansible_user: "{{ lookup('env', 'CISCO_USER') }}"
ansible_password: "{{ lookup('env', 'CISCO_PASS') }}"

ansible_command_timeout: 60
ansible_connect_timeout: 60
