name: NetDevOps CI/CD

on:
  push:
    paths:
      - 'playbooks/**'
      - 'configs/**'
      - 'inventory/**'
      - 'ansible.cfg'
      - 'requirements.yml'
      - 'test/**'
    branches:
      - main
  workflow_dispatch:

env:
  CISCO_USER: ${{ secrets.CISCO_USER }}
  CISCO_PASS: ${{ secrets.CSICO_USER }}

jobs:
  Validate:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Sync dependencies with uv
        run: |
          uv sync

      - name: Ansible Syntax Check
        run: |
          uv run ansible-playbook --syntax-check playbooks/*.yml -i inventory/ospf_lab.yml

  Backup:
    runs-on: self-hosted
    needs: Validate
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Sync Dependencies With uv
        run: |
          uv sync

      - name: Backup Configs
        run: |
          uv run ansible-playbook -i inventory/ospf_lab.yml playbooks/01_config_backup.yml

      - name: Upload Backup Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iosxe-config-backups
          path: backups/

  Deploy:
    runs-on: self-hosted
    needs: Backup
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
 
      - name: Download Backup Artifacts
        uses: actions/download-artifact@v4
        with:
          name: iosxe-config-backups
          path: backups/
          uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Sync Dependencies With uv
        run: |
          uv sync

      - name: Deploy Changes
        run: |
          uv run ansible-playbook -i inventory/ospf_lab.yml playbooks/02_ntp_config.yml

  Tests:
    runs-on: self-hosted
    needs: Deploy
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Sync Dependencies With uv
        run: |
          uv sync

      - name: Run pyATS Tests
        run: |
          uv run pyats run job tests/job.py --no-mail --no-archive --testbed tests/testbed.yaml
