name: NetDevOps CI/CD

on:
  push:
    paths:
      - 'playbooks/**'
      - 'configs/**'
      - 'inventory/**'
      - 'ansible.cfg'
      - 'requirements.yml'
    branches:
      - main
  workflow_dispatch:

env:
  CISCO_USER: ${{ secrets.CISCO_USER }}
  CISCO_PASS: ${{ secrets.CSICO_USER }}

jobs:
  validate:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Sync dependencies with uv
        run: |
          uv sync

      - name: Ansible Syntax Check
        run: |
          uv run ansible-playbook --syntax-check playbooks/*.yml -i inventory/ospf_lab.yml

  deploy:
    runs-on: self-hosted
    needs: validate
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Sync dependencies with uv
        run: |
          uv sync

      - name: Deploy configs
        run: |
          uv run ansible-playbook -i inventory/ospf_lab.yml playbooks/02_ntp_config.yml

  test:
    runs-on: self-hosted
    needs: deploy
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Sync dependencies with uv
        run: |
          uv sync

      - name: Run pyATS tests
        run: |
          uv run pyats run job tests/job.py

